#!/bin/bash
#
# extract-text: extract plaintext from Wikipedia dump files (xml.bz2).
#
# "/data" directory is exposed by Dockerfile:
#
#   - VOLUME [ "/data" ]
#   - WORKDIR /data
#
#----------
#    Dockerized wikipedia-dump-tools
#    Copyright (C) 2014  William Yeh <william.pjyeh@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#----------


if [ $# -lt 2 ]; then
    echo "extract-text: extract plaintext from Wikipedia dump files (xml.bz2)."
    echo "Usage: extract-text  <input_file>  <output_file>  [log_file]"
    exit 1
fi



if [ $# -eq 2 ]; then

	python -m wikitools.pageprocessor --continue-on-error \
	    $1 \
	    wikitools.examples.print_text \
	    wikitools.transforms.convert_to_plain_text \
	    > $2

else

	python -m wikitools.pageprocessor --continue-on-error \
	    --log $3 \
	    $1 \
	    wikitools.examples.print_text \
	    wikitools.transforms.convert_to_plain_text \
	    > $2

fi