#!/bin/bash
#
# extract-text: extract plaintext from Wikipedia dump files (xml.bz2).
#
# "/data" directory is exposed by Dockerfile:
#
#   - VOLUME [ "/data" ]
#   - WORKDIR /data
#


if [ $# -lt 2 ]; then
    echo "extract-text: extract plaintext from Wikipedia dump files (xml.bz2)."
    echo "Usage: extract-text  <input_file>  <output_file>  [log_file]"
    exit 1
fi



if [ $# -eq 2 ]; then

	python -m wikitools.pageprocessor --continue-on-error \
	    $1 \
	    wikitools.examples.print_text \
	    wikitools.transforms.convert_to_plain_text \
	    > $2

else

	python -m wikitools.pageprocessor --continue-on-error \
	    --log $3 \
	    $1 \
	    wikitools.examples.print_text \
	    wikitools.transforms.convert_to_plain_text \
	    > $2

fi